language: php

php:
  - "5.5"
  - "5.6"
  - "7.0"

before_script:
  - composer self-update
  - composer install --no-scripts --no-interaction --dev
  - composer dump-autoload -o

after_script:
    - php vendor/bin/coveralls -v

script:
    - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
